development:
  adapter: postgresql
  database: database_development
  host: localhost
  pool: 5
  timeout: 5000
  username: myapp
  password: asdasd123


test:
  adapter: postgresql
  database: database_test
  pool: 5
  timeout: 5000
  username: myapp
  password: asdasd123


production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
